# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - trelloserver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_bfda43a230f1432a9b0e3c67c4c62e9f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_adddbec5786a4849a900f377aa1140b9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bfda43a230f1432a9b0e3c67c4c62e9f }}/trello-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'trelloserver'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_26f8ae8626fe4a4287cb7f52e0121f0f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bfda43a230f1432a9b0e3c67c4c62e9f }}/trello-server:${{ github.sha }}'